<?php

namespace Tycoon\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRestaurantRepository extends EntityRepository
{
}
