tycoon_api_restaurant:
    resource:   "@TycoonApiBundle/Controller/RestaurantController.php"
    type:       annotation

tycoon_api_user:
    resource:   "@TycoonApiBundle/Controller/UserController.php"
    type:       annotation